holycodex_version = "0.17.0"
repository = "https://github.com/openai/codex.git"
commit = "a956835d020762cb2b570053af06f643a11c0ecc"
release = "rust-v0.160.0"
patch_series_format = 1
codex_workspace = "codex-rs"
