// SPDX-License-Identifier: Apache-2.0

export { CLI_SCHEMA_VERSION, STATE_SCHEMA_EPOCH, packageName } from "./common.ts";
export type { JsonObject, JsonPrimitive, JsonValue, SafeDetails } from "./common.ts";
export { decodeModelWire, encodeModelWire } from "./model-wire.ts";
export { CoreError } from "./errors.ts";
export type { CoreErrorCode, CoreResult } from "./errors.ts";
export { decodeUnknown } from "./schema.ts";

export {
  CAPABILITY_REGISTRY,
  CAPABILITY_APPLICABILITY,
  CapabilityNameSchema,
  CapabilityHealthSchema,
  CapabilityProviderStatusSchema,
  OFFICIAL_OPENAI_CURATED_MARKETPLACE_NAMES,
  OFFICIAL_OPENAI_CURATED_PLUGIN_NAMES,
  DEFAULT_CAPABILITY_SELECTIONS,
  DEFAULT_OPTIONAL_CAPABILITY_SELECTIONS,
  CORE_SEMANTIC_SKILL_IDS,
  FRONTEND_CAPABILITY_APPLICABILITY,
  OPTIONAL_CAPABILITY_NAMES,
  OptionalCapabilityNameSchema,
  canonicalOfficialPluginId,
  capabilityHealth,
  migrateOptionalCapabilitySelections,
  officialPluginIdCandidates,
  pluginIdsForOptionalCapabilities,
  resolveOfficialPluginIdentity,
  resolveOptionalCapabilitySelections,
} from "./capabilities.ts";
export type {
  CapabilityName,
  CapabilityApplicability,
  CapabilityDefaults,
  CapabilityDefinition,
  CapabilityHealth,
  CapabilityProviderStatus,
  OfficialOpenAiCuratedMarketplaceName,
  OfficialOpenAiCuratedPluginName,
  OfficialPluginIdentity,
  ExplicitOptionalCapabilitySelections,
  OptionalCapabilityName,
  OptionalCapabilitySelections,
} from "./capabilities.ts";

export {
  APPROVAL_POLICY,
  APPROVAL_POLICY_GUIDANCE,
  ApprovalModeSchema,
  ApprovalPolicyActionSchema,
  ApprovalPolicyEntrySchema,
  ApprovalPolicySchema,
  approvalModeFor,
  lookupApprovalPolicy,
} from "./approval-policy.ts";
export type {
  ApprovalMode,
  ApprovalPolicy,
  ApprovalPolicyAction,
  ApprovalPolicyEntry,
} from "./approval-policy.ts";

export {
  createProjectId,
  createRunId,
  createSha256Digest,
  createTrustId,
  ProjectIdentityInputSchema,
  RunIdentityInputSchema,
  SchemaEpochIdSchema,
  TrustIdentityInputSchema,
  parseIdentityInput,
  parseSchemaEpochId,
} from "./identifiers.ts";
export type {
  IdentityRecord,
  ProjectId,
  ProjectIdentityInput,
  RunId,
  RunIdentityInput,
  SchemaEpochId,
  Sha256Digest,
  TrustId,
  TrustIdentityInput,
} from "./identifiers.ts";

export {
  EffortSchema,
  ForkTurnsSchema,
  context7RequiredForAssignment,
  Context7EvidenceStateSchema,
  CREDENTIAL_INTERACTION_POLICY,
  FILESYSTEM_ACCESS_SCHEMA,
  GENERIC_BUILTIN_AGENT_TYPES,
  ExplorerTaskSchema,
  LegacyProfileNameSchema,
  LibrarianTaskSchema,
  migrateProfileName,
  ProfileNameSchema,
  ProfileNameMigrationSchema,
  ProfileSelectionSchema,
  RootDirectExecutionExceptionSchema,
  RootExecutionStateSchema,
  RootOwnedAuthoritySchema,
  ROOT_ORCHESTRATION_POLICY,
  FRONTEND_WORKFLOW_POLICY,
  LIBRARIAN_CONTEXT7_POLICY,
  SECURITY_WORKFLOW_POLICY,
  TESTING_POLICY,
  NO_SOURCE_MUTATION_RULE,
  SURGICAL_MUTATION_RULE,
  NATIVE_AGENT_TYPES,
  NativeAgentTypeSchema,
  ReviewerTaskSchema,
  RoleSchema,
  RoleTaskSchema,
  ROLE_DEFINITIONS,
  ROUTE_KEYS,
  RouteKeySchema,
  ServiceTierSchema,
  WorkerTaskSchema,
  lookupRoleDefinition,
  nativeAgentTypeFor,
  rootDirectExecutionAllowed,
  rootExecutionState,
  taskPermissionsFor,
  taskDescriptionFor,
  taskInstructionFor,
} from "./routes.ts";
export type {
  Effort,
  ForkTurns,
  Context7AssignmentSemantics,
  Context7EvidenceState,
  FilesystemAccess,
  GenericBuiltinAgentType,
  ExplorerTask,
  LegacyProfileName,
  ProfileNameMigrationInput,
  ProfileName,
  ProfileSelection,
  LibrarianTask,
  RootDirectExecutionException,
  RootExecutionState,
  RootOwnedAuthority,
  NativeAgentType,
  Role,
  RoleDefinition,
  RoleTask,
  ReviewerTask,
  RouteKey,
  ServiceTier,
  TaskForRole,
  TaskSlot,
  SpecialistTaskPermissions,
  WorkerTask,
} from "./routes.ts";
export type { ProfileDefinition, RouteDefinition } from "./routes.ts";

export {
  CliEnvelopeSchema,
  CliFailureEnvelopeSchema,
  CliSuccessEnvelopeSchema,
  SPECIALIST_OUTCOME_VERSION,
  SpecialistOutcomeV2BaseSchema,
  CapabilityResultV2Schema,
  Context7EvidenceSchema,
  normalizeSpecialistOutcome,
  parseCapabilityResultV2,
  parseCliEnvelope,
  parseSpecialistOutcome,
  parseSpecialistOutcomeV2,
  specialistOutcomeFromCapabilityResult,
  SpecialistOutcomeSchema,
  SpecialistOutcomeV2Schema,
  SpecialistStatusSchema,
  SuggestedLunaEffortSchema,
} from "./envelopes.ts";
export type {
  CliEnvelope,
  CliFailureEnvelope,
  CliSuccessEnvelope,
  SpecialistOutcome,
  SpecialistOutcomeV2,
  CapabilityResultV2,
  Context7Evidence,
  SpecialistOutcomeV2Base,
  SpecialistOutcomeV2ForRole,
  ExplorerOutcome,
  LibrarianOutcome,
  WorkerOutcome,
  ReviewerOutcome,
  SpecialistStatus,
  SuggestedLunaEffort,
} from "./envelopes.ts";

export {
  ASTRA_MODEL_ID,
  LUNA_MODEL_ID,
  lookupProfile,
  lookupRoute,
  parseProfileSelection,
  PROFILE_CATALOG,
  ROUTE_EFFORT_OVERRIDES,
  resolveProfileSelection,
} from "./catalog.ts";

export {
  canonicalIdentityUtf8,
  canonicalJson,
  canonicalJsonUtf8,
  composeDigestInput,
  domainSeparatedSha256,
  sha256DomainDigest,
} from "./canonical.ts";

export {
  ASSIGNMENT_SCHEMA_VERSION,
  AssignmentOwnerSchema,
  AssignmentResultInputSchema,
  AssignmentOutcomeSchema,
  InvocationSchema,
  CreateAssignmentInputSchema,
  ReviseAssignmentScopeInputSchema,
  VcsIntegrationInputSchema,
  CreateIntentInputSchema,
  AssignmentSchema,
  AssignmentStatusSchema,
  EvidenceSchema,
  INTENT_SCHEMA_VERSION,
  IntentEvidenceInputSchema,
  IntentSchema,
  IntentStateSchema,
  IntentStore,
  IntentStoreError,
  PLAN_SCHEMA_VERSION,
  PlanInputSchema,
  PlanSchema,
  RepositoryBaselineSchema,
  TOON_COMPATIBILITY,
  readRepositorySnapshot,
} from "./work-state.ts";
export type {
  Assignment,
  AssignmentOwner,
  AssignmentInvocation,
  AssignmentOutcome,
  AssignmentResultInput,
  AssignmentStatus,
  CompletionRefusal,
  CreateAssignmentInput,
  ReviseAssignmentScopeInput,
  VcsIntegrationInput,
  CreateIntentInput,
  Intent,
  IntentEvidenceInput,
  IntentEvidence,
  IntentPlan,
  IntentState,
  IntentStoreOptions,
  PlanInput,
  RepositoryBaseline,
  RepositorySnapshot,
  StoreErrorCode,
} from "./work-state.ts";
