// SPDX-License-Identifier: Apache-2.0

export const SYMBOL_KIND_MAP: Readonly<Record<number, string>> = Object.freeze({
  1: "File",
  2: "Module",
  3: "Namespace",
  4: "Package",
  5: "Class",
  6: "Method",
  7: "Property",
  8: "Field",
  9: "Constructor",
  10: "Enum",
  11: "Interface",
  12: "Function",
  13: "Variable",
  14: "Constant",
  15: "String",
  16: "Number",
  17: "Boolean",
  18: "Array",
  19: "Object",
  20: "Key",
  21: "Null",
  22: "EnumMember",
  23: "Struct",
  24: "Event",
  25: "Operator",
  26: "TypeParameter",
});
export const SEVERITY_MAP: Readonly<Record<number, string>> = Object.freeze({
  1: "error",
  2: "warning",
  3: "information",
  4: "hint",
});

export const EXT_TO_LANG: Readonly<Record<string, string>> = Object.freeze({
  ".c": "c",
  ".cpp": "cpp",
  ".cxx": "cpp",
  ".cc": "cpp",
  ".c++": "cpp",
  ".h": "c",
  ".hpp": "cpp",
  ".hh": "cpp",
  ".hxx": "cpp",
  ".h++": "cpp",
  ".cs": "csharp",
  ".css": "css",
  ".dart": "dart",
  ".dockerfile": "dockerfile",
  ".ex": "elixir",
  ".exs": "elixir",
  ".fs": "fsharp",
  ".fsi": "fsharp",
  ".fsx": "fsharp",
  ".go": "go",
  ".hs": "haskell",
  ".lhs": "haskell",
  ".html": "html",
  ".htm": "html",
  ".java": "java",
  ".jl": "julia",
  ".js": "javascript",
  ".jsx": "javascriptreact",
  ".json": "json",
  ".jsonc": "jsonc",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".lua": "lua",
  ".md": "markdown",
  ".m": "objective-c",
  ".mm": "objective-cpp",
  ".php": "php",
  ".pl": "perl",
  ".pm": "perl",
  ".ps1": "powershell",
  ".py": "python",
  ".pyi": "python",
  ".rb": "ruby",
  ".rake": "ruby",
  ".rs": "rust",
  ".scss": "scss",
  ".sh": "shellscript",
  ".bash": "shellscript",
  ".zsh": "shellscript",
  ".sql": "sql",
  ".svelte": "svelte",
  ".swift": "swift",
  ".ts": "typescript",
  ".tsx": "typescriptreact",
  ".mts": "typescript",
  ".cts": "typescript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".vue": "vue",
  ".zig": "zig",
  ".zon": "zig",
  ".astro": "astro",
  ".ml": "ocaml",
  ".mli": "ocaml",
  ".tf": "terraform",
  ".tfvars": "terraform-vars",
  ".hcl": "hcl",
  ".nix": "nix",
  ".typ": "typst",
  ".typc": "typst",
  ".prisma": "prisma",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".graphql": "graphql",
  ".gql": "graphql",
  ".clj": "clojure",
  ".cljs": "clojure",
  ".cljc": "clojure",
  ".edn": "clojure",
});

/** Maps an effective extension to the LSP language id. */
export function getLanguageId(extension: string): string {
  return EXT_TO_LANG[extension.toLowerCase()] ?? "plaintext";
}
