// SPDX-License-Identifier: Apache-2.0

export {
  CODEX_CLIENT_VERSION,
  CODEX_PROTOCOL_EPOCH,
  CODEX_PROTOCOL_VERSION,
  DEFAULT_MAX_DIAGNOSTIC_BYTES,
  DEFAULT_MAX_LINE_BYTES,
  packageName,
} from "./common";
export { CodexError } from "./common";
export type { CodexErrorCode, CodexFailureKind, CodexResult } from "./common";
export type {
  GeneratedClientNotification,
  GeneratedClientRequest,
  GeneratedServerNotification,
  GeneratedServerRequest,
} from "./generated-wire";
export {
  GENERATED_APPROVAL_REQUEST_METHODS,
  GENERATED_DYNAMIC_TOOL_REQUEST_METHODS,
  GENERATED_ELICITATION_REQUEST_METHODS,
  GENERATED_INITIALIZED_NOTIFICATION,
  GENERATED_MULTI_AGENT_V2_LIFECYCLE_STATUS,
  generatedMultiAgentV2LifecycleStatus,
  GENERATED_PERMISSION_REQUEST_METHODS,
  GENERATED_SERVER_REQUEST_METHODS,
  GENERATED_SUPPORTED_CLIENT_METHODS,
  GENERATED_TURN_COMPLETED_NOTIFICATION_METHOD,
} from "./generated-wire";

export {
  InitializedNotificationSchema,
  InitializeParamsSchema,
  InitializeResultSchema,
  ConfigReadParamsSchema,
  ConfigReadResultSchema,
  JsonRpcErrorResponseSchema,
  JsonRpcErrorSchema,
  JsonRpcNotificationSchema,
  JsonRpcRequestSchema,
  JsonRpcResponseSchema,
  RequestIdSchema,
  ModelListParamsSchema,
  ModelListResultSchema,
  ModelProviderCapabilitiesParamsSchema,
  ModelProviderCapabilitiesResultSchema,
  PermissionProfileListParamsSchema,
  PermissionProfileListResultSchema,
  ServerRequestSchema,
  ServerResponseSchema,
  SupportedUsageSchema,
  ThreadForkResultSchema,
  ThreadUnsubscribeParamsSchema,
  ThreadUnsubscribeResultSchema,
  ThreadIdentitySchema,
  ThreadListResultSchema,
  ThreadReadResultSchema,
  ThreadResumeResultSchema,
  ThreadStartResultSchema,
  ThreadStartParamsSchema,
  ThreadResumeParamsSchema,
  ThreadReadParamsSchema,
  ThreadListParamsSchema,
  ThreadForkParamsSchema,
  TurnCompletedNotificationSchema,
  TurnInterruptParamsSchema,
  TurnInterruptResultSchema,
  TurnStartParamsSchema,
  TurnStartResultSchema,
  TurnSteerParamsSchema,
  TurnSteerResultSchema,
  UsageCompletenessSchema,
} from "./protocol";
export type {
  InitializeParams,
  InitializeResult,
  ConfigReadParams,
  ConfigReadResult,
  ApprovalRequest,
  DynamicToolRequest,
  ElicitationRequest,
  JsonRpcError,
  JsonRpcErrorResponse,
  JsonRpcNotification,
  JsonRpcResponse,
  RequestId,
  ModelCapability,
  ModelListParams,
  ModelListResult,
  ModelProviderCapabilitiesParams,
  ModelProviderCapabilitiesResult,
  PermissionProfileListParams,
  PermissionProfileListResult,
  PermissionRequest,
  ServerRequest,
  ServerRequestCategory,
  ServerResponse,
  SupportedUsage,
  ThreadForkParams,
  ThreadForkResult,
  ThreadIdentity,
  ThreadListParams,
  ThreadListResult,
  ThreadReadParams,
  ThreadReadResult,
  ThreadResumeParams,
  ThreadResumeResult,
  ThreadStartParams,
  ThreadStartResult,
  ThreadUnsubscribeParams,
  ThreadUnsubscribeResult,
  TurnCompletedNotification,
  TurnIdentity,
  TurnInterruptParams,
  TurnInterruptResult,
  TurnStartParams,
  TurnStartResult,
  TurnSteerParams,
  TurnSteerResult,
  UsageCompleteness,
  CodexNotification,
} from "./protocol";

export { AppServerClient } from "./client";
export type { AppServerClientOptions, ServerRequestHandler } from "./client";

export { BunStdioTransport, createAllowlistedEnvironment, sanitizeDiagnostics } from "./transport";
export type { AsyncLineTransport, BunStdioTransportOptions } from "./transport";

export { discoverCodexExecutable, generateCodexSchemas } from "./executable";
export type {
  CodexExecutableDiscoveryOptions,
  CodexExecutableIdentity,
  CommandResult,
  CommandRunner,
  SchemaGenerationOptions,
  SchemaGenerationProvenance,
} from "./executable";

export { verifyGeneratedArtifact } from "./generated-artifact";
export type {
  GeneratedArtifactFile,
  GeneratedArtifactInventory,
  GeneratedArtifactVerification,
  GeneratedArtifactVerificationOptions,
} from "./generated-artifact";

export {
  cleanupManagedConfig,
  compareBeforeManagedWrite,
  createManagedConfigState,
  ManagedConfigEntrySchema,
  ManagedConfigMetadataSchema,
  ManagedConfigStateSchema,
  mergeManagedConfig,
} from "./managed-config";
export type {
  ManagedConfigCleanup,
  ManagedConfigEntry,
  ManagedConfigMetadata,
  ManagedConfigState,
  ManagedWriteDecision,
} from "./managed-config";

export {
  cleanupManagedRuntimeConfig,
  compareManagedConfigKey,
  createManagedRuntimeConfigState,
  deleteTomlPath,
  HOLYCODEX_AGENT_TYPES,
  isLegacyManagedConfigKeyPath,
  isManagedConfigKeyPath,
  isManagedRuntimeConfigState,
  LEGACY_MANAGED_CONFIG_KEY_PATHS,
  ManagedConfigKeyPathSchema,
  ManagedConfigOriginalValueSchema,
  ManagedConfigSafeValueSchema,
  ManagedRuntimeConfigEntrySchema,
  ManagedRuntimeConfigStateSchema,
  migrateLegacyManagedRuntimeConfig,
  mergeManagedRuntimeConfig,
  normalizeRelativeConfigPath,
  readTomlPath,
  resolveAgentConfigPath,
  summarizeManagedConfigValue,
  TomlDocumentSchema,
  TomlValueSchema,
  writeTomlPath,
  ROOT_CONFIG_KEY_PATHS,
} from "./runtime-config";
export type {
  AgentConfigKeyPath,
  HolyCodexAgentType,
  ManagedConfigKeyPath,
  LegacyManagedConfigKeyPath,
  ManagedConfigStateKeyPath,
  ManagedConfigOriginalValue,
  ManagedConfigSafeValue,
  ManagedConfigWriteValue,
  ManagedRuntimeConfigCleanup,
  ManagedRuntimeConfigEntry,
  ManagedRuntimeConfigMerge,
  ManagedRuntimeConfigLegacyMigration,
  ManagedRuntimeConfigState,
  ManagedConfigDrift,
  RootConfigKeyPath,
  TomlDocument,
  TomlTable,
  TomlValue,
} from "./runtime-config";

export {
  createOfficialPluginAdapter,
  OfficialPluginManifestSchema,
  OfficialPluginIdSchema,
  OfficialPluginSelectionSchema,
  LiveOfficialPluginEntrySchema,
  LiveOfficialPluginListEnvelopeSchema,
  parseOfficialPluginManifest,
  parseLiveOfficialPluginList,
  selectOfficialPlugins,
  verifyOfficialPluginManifest,
  verifyOfficialPluginManifestFile,
  bootstrapOfficialMarketplace,
  parseOfficialMarketplaceSnapshot,
  provisionOfficialMarketplaceSnapshot,
  readOfficialMarketplaceSnapshot,
  resolveOfficialPluginEntry,
  isRecognizedOfficialPluginName,
  OFFICIAL_CURATED_MARKETPLACE_NAME,
  OFFICIAL_CURATED_MARKETPLACE_SOURCE,
} from "./official-plugins";
export type {
  LiveOfficialPluginEntry,
  LiveOfficialPluginListEnvelope,
  OfficialPluginAdapter,
  OfficialPluginAdapterOptions,
  OfficialPluginCommandRunner,
  OfficialPluginId,
  OfficialPluginManifest,
  OfficialPluginSelection,
  OfficialPluginVerification,
  OfficialMarketplaceBootstrapOptions,
  OfficialMarketplaceGitFallbackOptions,
  OfficialMarketplacePluginEntry,
  OfficialMarketplaceProvisionOptions,
  OfficialMarketplaceRuntimeClose,
  OfficialMarketplaceSnapshot,
  ResolvedOfficialPluginEntry,
} from "./official-plugins";
export { OfficialPluginAdapterError } from "./official-plugins";
