// SPDX-License-Identifier: Apache-2.0

export const packageName = "@holycodex/workflow-host" as const;

export { WorkflowHostError } from "./errors.ts";
export type { WorkflowHostErrorCode } from "./errors.ts";
export {
  COST_UNIT_SCALE,
  CostAccountingError,
  LONG_CONTEXT_INPUT_THRESHOLD,
  PRICING_REGISTRY,
  PRICING_VERSION,
  conservativeSettlement,
  costMaxToUnits,
  costUnitsToDisplay,
  estimatePlanCost,
  estimateRouteCost,
  pricingFor,
  settleUsage,
} from "./cost.ts";
export type {
  CostEstimate,
  CostJournal,
  CostSettlement,
  CostUnits,
  PricingEntry,
  PricingKey,
  PricingRate,
  TokenCounts,
} from "./cost.ts";
export { decodeStoredJournalEvent, FileRunStore } from "./store.ts";
export type { IntegrityDiagnostic, RevisionCommitBuilder, StoredRun } from "./store.ts";
export { WorkflowHost } from "./host.ts";
export {
  assertNativeWorkflowIdentity,
  buildNativeWorkflowIdentity,
  classifyCompatibilityCardinality,
  compatibilityProofDigest,
  operationFingerprint,
} from "./identity.ts";
export type { NormalizedOperationInput } from "./identity.ts";
export type {
  ContinuationDecision,
  CreateRunInput,
  HostCapacity,
  ProjectTrustInput,
  ReplayAdmission,
  ReplayDecision,
  RefinementOperation,
  RetainedReuseDecision,
  RetainedReuseInput,
  RunExecution,
  RunInput,
  RuntimeEvaluator,
  WorkflowDefinition,
  WorkflowExecutionMode,
  WorkflowHostServices,
  HostApprovalDecision,
  HostApprovalHandler,
  HostVerificationHandler,
  HostCheckpointHandler,
  SpecialistAssignment,
  SpecialistExecutor,
  TelemetrySink,
  WorkflowHostOptions,
} from "./types.ts";
export {
  CheckpointSchema,
  CompatibilityCardinalitySchema,
  ContinuationClaimSchema,
  ContinuationPacketSchema,
  IdentityComponentsSchema,
  NativeWorkflowIdentitySchema,
  InspectionProjectionSchema,
  JsonObjectSchema,
  JsonValueSchema,
  JournalEventSchema,
  OperationInputSchema,
  OperationCostAccountingSchema,
  OperationLifecycleSchema,
  ProjectTrustRefSchema,
  RefinementProposalSchema,
  RefinementSchema,
  RetainedContextIdentitySchema,
  RetainedContextStatusSchema,
  RetainedSessionRefSchema,
  RunDefinitionSchema,
  RunSnapshotSchema,
  RunStatusSchema,
  SchemaEpochsSchema,
  TelemetrySchema,
  WorkflowDescriptorSchema,
  WorkflowProjectionSchema,
  WorkflowExecutionModeSchema,
  WorkflowExecutionIdentitySchema,
  WORKFLOW_HOST_SCHEMA_EPOCH,
  WORKFLOW_HOST_SCHEMA_EPOCHS,
  decodeHostSchema,
} from "./schemas.ts";
export type {
  Checkpoint,
  CompatibilityCardinality,
  ContinuationClaim,
  ContinuationPacket,
  IdentityComponents,
  NativeWorkflowIdentity,
  InspectionProjection,
  JournalEvent,
  OperationInput,
  OperationLifecycle,
  OperationState,
  ProjectTrustRef,
  Refinement,
  RefinementProposal,
  RetainedContextIdentity,
  RetainedContextStatus,
  RetainedSessionRef,
  RunDefinition,
  RunId,
  RunSnapshot,
  RunStatus,
  SchemaEpochs,
  Telemetry,
  WorkflowDescriptor,
  WorkflowProjection,
  WorkflowExecutionIdentity,
} from "./schemas.ts";
